### ISSUE TITLE
CUDA error for sampling of gpu tensor without replacement

### ISSUE THREAD

**Issue by bzapf** [LeviViana/torch_sampling#6]
Hi,
first of all - thank you for providing this really useful code, makes my computations much more efficient! 

I moved to a different remote GPU and I ran into a CUDA error with choice:

```Traceback (most recent call last):
  File "testchoice.py", line 14, in <module>
    print(choice(x, 2, False))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

The script used is
```
import torch
from torch_sampling import choice

x = torch.arange(10)

print(choice(x, 2, True))
print(choice(x, 2, False))

print("cpu worked")

x = x.cuda()

print(choice(x, 2, True))
print(choice(x, 2, False))

print("gpu worked")
```
The script works on one of my remote machines (CUDA Version 11.4, PyTorch 1.7.0., GeForce RTX 2080 Ti) but sampling without replacement fails on another (CUDA Version 11.0, PyTorch 1.7.0, Tesla T4), the output is

```
tensor([8, 0])
tensor([5, 1])
cpu worked
tensor([4, 6], device='cuda:0')
```
Thanks in advance for any help!

**Comment by LeviViana** [comment]
Hi! Thanks for the feedback! I didn't test this extension on these versions of CUDA drivers, so I'm not surprised it doesn't work well. 

```shell
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

I've already got this error before, on another context, and actually it comes from the fact that the code was compiled for one GPU (a recent one, like 3070 RTX), and called by another one (an older one, like 2080 Ti). I guess that if you run something like `CUDA_VISIBLE_DEVICES=1 python setup.py develop` (assuming the GPU 1 is the one triggering the bug), then It will probably solve the issue (it solved for me).

I know it's ugly, but right now I don't have the time to solve the issue properly, so the easiest solution is to setup different environments, one for each kind of GPU, and not forget to pass `CUDA_VISIBLE_DEVICES` at each python script call. Tell me if it helps !

**Comment by bzapf** [comment]
Hi,
thank you for your fast and helpful response! Your hint was going in the right direction, the code was compiled for a T4, and the problem was then occurring on a V100. I've installed from scratch on the machine with the V100, and now it works!
